services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: replog-caddy
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/datad
      - caddy_config:/config

  gym:
    build: .
    container_name: replog
    restart: unless-stopped

  database:
    image: postgres:16-alpine
    container_name: replog-postgres
    ports:
      - "15432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
      POSTGRES_DB: gymdb

volumes:
  caddy_data:
  caddy_config: