services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: gym-tracker-user
      POSTGRES_PASSWORD: gym-tracker-password
      POSTGRES_DB: gym-tracker-db

    ports:
      - "0.0.0.0:6000:5432"

    volumes:
      # persistent database storage
      - postgres_data:/var/lib/postgresql/data

      # auto-run schema on first startup
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: