services:
  caddy:
    image: caddy:2.8.4-alpine
    container_name: replog-caddy
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/datad
      - caddy_config:/config

  gym:
    build: .
    container_name: replog
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: